language: php
php:
  - '7.2'
dist: xenial
# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
# Commands you want to run that will verify your build.
script: phpunit
# require the branch name to be master (note for PRs this is the base branch name)
if: branch = master